start.docker.compose.for.iceberg:
	# Run the docker-compose file for iceberg
	docker-compose -f docker-compose.yaml up -d

stop.docker.compose.for.iceberg:
	# Stop the docker-compose file for iceberg
	docker-compose -f docker-compose.yaml down

open.jupyter.web:
	# Open Jupyter web interface
	open http://localhost:8888/tree/notebooks

open.min.io.web:
	# Open MinIO web interface
	open http://localhost:9001

